config/routes.rb
Rails.application.routes.draw do
  # get 'students/create'
  # get 'students/show'
  # get 'students/update'
  # get 'students/index'
  # get 'students/destroy'
  resources :students
  resources :exams

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
    def new #untuk menampilkan form data baru
      @exams = Exams.new
    end
  
    def create #untuk memproses data baru yang dimasukan di form new
      #render plain: params.inspect cara mengecek apa isi params
      #title = params [:book][:title] cara mngecek balikan params
      exams = Exams.new(resource_params)
      Exams.save 
      flash[:notice] = 'Exam has been created'
      redirect_to exams_path
    end
  
    def edit #menampilkan data yang sudah disimpan di edit
      id = params[:id]
      @exams = Exams.find(id)
    end
  
    def update #melakuka prses ketika user mengedit data
      id = params[:id]
      @exams = Exams.find(params[:id])
      @exams.update(resource_params)
      flash[:notice] = 'Exam has been update'
        redirect_to exams_path(@exams)
      
    end
  
    def destroy #untuk menghapus data
       id = params[:id]
       exams = exams.find(params[:id])
       exams.destroy
       flash[:notice] = 'Exam has been delete'
       redirect_to exams_path
    end
  
    def index #menampilkan seluruh data yang ada di database
      @exams = exams.all
    end
  
    def show #menampilkan sebuah data secara detail
      id = params[:id]
      @exams = exams.find (id)
      # render plain : id
      # render plain : @book.title
  
    end
  private
  def resource_params
    params.require(:exams).permit(:title, :mapel, :duration, :nilai, :keterangan, :level, :student_id)
  end
  end
  

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new #untuk menampilkan form data baru
    @student = Student.new
  end

  def create #untuk memproses data baru yang dimasukan di form new
    #render plain: params.inspect cara mengecek apa isi params
    #title = params [:book][:title] cara mngecek balikan params
    student = Student.new(resource_params)
    student.save 
    flash[:notice] = 'Student has been created'
    redirect_to students_path
  end

  def edit #menampilkan data yang sudah disimpan di edit
    id = params[:id]
    @student = Student.find(id)
  end

  def update #melakuka prses ketika user mengedit data
    id = params[:id]
    @student = Student.find(params[:id])
    @student.update(resource_params)
    flash[:notice] = 'Student has been update'
      redirect_to students_path(@book)
    
  end

  def destroy #untuk menghapus data
     id = params[:id]
     student = Student.find(params[:id])
     student.destroy
     flash[:notice] = 'student has been delete'
     redirect_to students_path
  end

  def index #menampilkan seluruh data yang ada di database
    @students = Student.all
  end

  def show #menampilkan sebuah data secara detail
    id = params[:id]
    @student = Student.find (id)
    # render plain : id
    # render plain : @book.title

  end
private
def resource_params
  params.require(:student).permit(:name, :username, :age, :rombel, :address, :city, :nik)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/exams/destroy.html.erb
<%= form_for (@Exams) do |f| %>
<%= f.label :title %> </br>
<%= f.text_field :title %> </br>

<%= f.label :mapel %> </br>
<%= f.text_field :mapel %> </br>

<%= f.label :duration %> </br>
<%= f.text_field :duration %> </br>

<%= f.label :nilai %> </br>
<%= f.text_field :nilai %> </br>

<%= f.label :keterangan %> </br>
<%= f.text_field :keterangan %> </br>

<%= f.label :level %> </br>
<%= f.text_field :level %> </br>

<%= f.label :student_id %> </br>
<%= f.text_field :student_id %> </br>



<%= f.submit "Save" %> 
<% end %>

app/views/exams/edit.html.erb
<%= form_for (@Exams) do |f| %>
<%= f.label :title %> </br>
<%= f.text_field :title %> </br>

<%= f.label :mapel %> </br>
<%= f.text_field :mapel %> </br>

<%= f.label :duration %> </br>
<%= f.text_field :duration %> </br>

<%= f.label :nilai %> </br>
<%= f.text_field :nilai %> </br>

<%= f.label :keterangan %> </br>
<%= f.text_field :keterangan %> </br>

<%= f.label :level %> </br>
<%= f.text_field :level %> </br>

<%= f.label :student_id %> </br>
<%= f.text_field :student_id %> </br>



<%= f.submit "Save" %> 
<% end %>

app/views/exams/index.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<h1>Halaman Exam</h1>

<table border="1">
    <tr>
        <td align="center">Title</td>
        <td align="center">Mapel</td>
         <td align="center">Duration</td>
          <td align="center">Nilai</td>
        <td align="center">Keterangan</td>
         <td align="center">Level</td>
          <td align="center">Student_ID</td>
         <td align="center" colspan="3">Action</td>
    </tr>
    <% @exams.each do |Exams| %>
        <tr>
            <td><%= Exams.title %></td>
            <td><%= Exams.mapel %></td>
             <td><%= Exams.duration %></td>
              <td><%= Exams.nilai %></td>
               <td><%= Exams.keterangan %></td>
                <td><%= Exams.level %></td>
                 <td><%= Exams.student_id %></td>
            <td><%= link_to 'Detail',Exams_path(Exams) %></td>
             <td><%= link_to 'Edit',edit_Exams_path(Exams) %></td>
              <td><%= link_to 'Delete',Exams_path(Exams), method: :delete, data: {confirm: 'are you sure for delete this file?'} %></td>
            </tr>
            <% end %>
        </table>

<%= link_to 'New Exam', new_Exams_path %>

app/views/exams/new.html.erb
<%= form_for (@Exams) do |f| %>
<%= f.label :title %> </br>
<%= f.text_field :title %> </br>

<%= f.label :mapel %> </br>
<%= f.text_field :mapel %> </br>

<%= f.label :duration %> </br>
<%= f.text_field :duration %> </br>

<%= f.label :nilai %> </br>
<%= f.text_field :nilai %> </br>

<%= f.label :keterangan %> </br>
<%= f.text_field :keterangan %> </br>

<%= f.label :level %> </br>
<%= f.text_field :level %> </br>

<%= f.label :student_id %> </br>
<%= f.text_field :student_id %> </br>



<%= f.submit "Save" %> 
<% end %>

app/views/exams/show.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>


title : <%= @Exams.title %> </br>
mapel : <%= @Exams.mapel %> </br>

title : <%= @Exams.title %> </br>
mapel : <%= @Exams.mapel %> </br>

<%= link_to 'kembali ke halaman sebelumnya',exams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kejarid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/destroy.html.erb
<%= form_for (@student) do |f| %>
<%= f.label :name %> </br>
<%= f.text_field :name %> </br>

<%= f.label :username %> </br>
<%= f.text_field :username %> </br>

<%= f.label :age %> </br>
<%= f.text_field :age %> </br>

<%= f.label :rombel %> </br>
<%= f.text_field :rombel %> </br>

<%= f.label :address %> </br>
<%= f.text_field :address %> </br>

<%= f.label :city %> </br>
<%= f.text_field :city %> </br>

<%= f.label :nik %> </br>
<%= f.text_field :nik %> </br>



<%= f.submit "Save" %> 
<% end %>

app/views/students/edit.html.erb
<%= form_for (@student) do |f| %>
<%= f.label :name %> </br>
<%= f.text_field :name %> </br>

<%= f.label :username %> </br>
<%= f.text_field :username %> </br>

<%= f.label :age %> </br>
<%= f.text_field :age %> </br>

<%= f.label :rombel %> </br>
<%= f.text_field :rombel %> </br>

<%= f.label :address %> </br>
<%= f.text_field :address %> </br>

<%= f.label :city %> </br>
<%= f.text_field :city %> </br>

<%= f.label :nik %> </br>
<%= f.text_field :nik %> </br>



<%= f.submit "Save" %> 
<% end %>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>

<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>
<h1>Halaman Student</h1>

<table border="1">
    <tr>
        <td align="center">Name</td>
        <td align="center">Username</td>
         <td align="center">Age</td>
          <td align="center">Rombel</td>
        <td align="center">Address</td>
         <td align="center">City</td>
          <td align="center">NIK</td>
         <td align="center" colspan="3">Action</td>
    </tr>
    <% @students.each do |student| %>
        <tr>
            <td><%= student.name %></td>
            <td><%= student.username %></td>
             <td><%= student.age %></td>
              <td><%= student.rombel %></td>
               <td><%= student.address %></td>
                <td><%= student.city %></td>
                 <td><%= student.nik %></td>
            <td><%= link_to 'Detail',student_path(student) %></td>
             <td><%= link_to 'Edit',edit_student_path(student) %></td>
              <td><%= link_to 'Delete',student_path(student), method: :delete, data: {confirm: 'are you sure for delete this file?'} %></td>
            </tr>
            <% end %>
        </table>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<%= form_for (@student) do |f| %>
<%= f.label :name %> </br>
<%= f.text_field :name %> </br>

<%= f.label :username %> </br>
<%= f.text_field :username %> </br>

<%= f.label :age %> </br>
<%= f.text_field :age %> </br>

<%= f.label :rombel %> </br>
<%= f.text_field :rombel %> </br>

<%= f.label :address %> </br>
<%= f.text_field :address %> </br>

<%= f.label :city %> </br>
<%= f.text_field :city %> </br>

<%= f.label :nik %> </br>
<%= f.text_field :nik %> </br>



<%= f.submit "Save" %> 
<% end %>

app/views/students/show.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>


name : <%= @student.name %> </br>
username : <%= @student.username %> </br>

name : <%= @student.name %> </br>
username : <%= @student.username %> </br>

<%= link_to 'kembali ke halaman sebelumnya',students_path %>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>